"""RAG local data loader.

Reads from agents/_data/ directory generated by prepare_rag_data.py:
  agents/_data/
  +-- index.json
  +-- {docId}/
      +-- meta.json
      +-- structure.json (optional)
      +-- pages/{n}.txt
"""

import json
from pathlib import Path
from typing import Any

from ._logger import create_logger

logger = create_logger("loader")

# Path resolution: _loader.py is in agents/, _data/ is a sibling directory
RAG_ROOT = Path(__file__).parent / "_data"

logger.log(f"RAG_ROOT: {RAG_ROOT}")


def _read_json(file_path: Path) -> Any | None:
    """Read and parse a JSON file, return None if not found."""
    try:
        with open(file_path, "r", encoding="utf-8") as f:
            return json.load(f)
    except FileNotFoundError:
        return None
    except (json.JSONDecodeError, OSError) as e:
        logger.error(f"Failed to read {file_path}: {e}")
        return None


def _safe_doc_dir(doc_id: str) -> Path | None:
    """Validate doc_id and return the document directory path."""
    if not doc_id or doc_id in (".", "..") or "/" in doc_id or "\\" in doc_id:
        logger.error(f"Invalid doc_id: {doc_id}")
        return None
    doc_dir = (RAG_ROOT / doc_id).resolve()
    rag_root_resolved = RAG_ROOT.resolve()
    if not str(doc_dir).startswith(str(rag_root_resolved)):
        logger.error(f"doc_id escapes RAG_ROOT: {doc_id}")
        return None
    return doc_dir


def list_documents() -> list[dict]:
    """List all indexed documents with their metadata."""
    index_path = RAG_ROOT / "index.json"
    logger.log(f"listDocuments() reading: {index_path}")
    idx = _read_json(index_path)
    if not idx or not idx.get("documents"):
        logger.warn(f"listDocuments() returned empty. RAG_ROOT={RAG_ROOT}")
        return []
    docs = idx["documents"]
    logger.log(f"listDocuments() found {len(docs)} documents")
    return [{"docId": d["docId"], "meta": d.get("meta", {})} for d in docs]


def get_document_meta(doc_id: str) -> dict | None:
    """Get document metadata."""
    doc_dir = _safe_doc_dir(doc_id)
    if not doc_dir:
        return None
    return _read_json(doc_dir / "meta.json")


def get_document_structure(doc_id: str) -> dict | None:
    """Get document tree-structure index (optional, may not exist)."""
    doc_dir = _safe_doc_dir(doc_id)
    if not doc_dir:
        return None
    return _read_json(doc_dir / "structure.json")


def get_page_content(doc_id: str, pages: list[int]) -> list[dict]:
    """Read page content for specified page numbers (max 20)."""
    doc_dir = _safe_doc_dir(doc_id)
    if not doc_dir:
        return []
    results = []
    for page_num in pages[:20]:
        page_path = doc_dir / "pages" / f"{page_num}.txt"
        if page_path.exists():
            try:
                text = page_path.read_text(encoding="utf-8")
                results.append({"page": page_num, "content": text})
            except OSError:
                results.append({"page": page_num, "content": "(read error)"})
        else:
            results.append({"page": page_num, "content": "(page not found)"})
    return results


def get_rag_index() -> dict | None:
    """Get the full index.json content (for /rag-stats)."""
    return _read_json(RAG_ROOT / "index.json")


def parse_page_range(range_str: str) -> list[int]:
    """Parse page range string like '5-7,12,15-16' into a list of page numbers.

    Max 20 pages per call.
    """
    pages: set[int] = set()
    for part in str(range_str).split(","):
        part = part.strip()
        if not part:
            continue
        if "-" in part:
            try:
                start_str, end_str = part.split("-", 1)
                start = int(start_str)
                end = int(end_str)
                if start <= end:
                    safe_end = min(end, start + 19)
                    for i in range(start, safe_end + 1):
                        pages.add(i)
            except ValueError:
                continue
        else:
            try:
                n = int(part)
                if n > 0:
                    pages.add(n)
            except ValueError:
                continue
    return sorted(pages)[:20]
